
sudo: required
language: java

jdk:
  - oraclejdk7
  - oraclejdk8



script:
  - mvn clean cobertura:cobertura -Dtest=SerializableTest#decodeGolden -DfailIfNoTests=false

before_deploy:
- tar -zcvf coverage-result.tar.gz /home/travis/build/leusonmario/wire/target/site/cobertura

deploy:
  provider: releases
  api_key:
    secure: "v6ImLbb5y2QHBaI3YlncdyGuUC2vlkNl2fUrze3HaQ4yUYgf8dK7mn8aQkbVK7+WJG90zBVnQXqa/VG2/oq1TAoOpwQfgPah/mY0uSZ2JMPsPZr1LamAEtGoJFeb+xnkoVMR93xjh+GKr5rxRApSjQmlrw1/eAPeQydK/L7FPPnVQCEOBXT5WmZR7c/nDJga8icPsr8O0obo3Wq0nobGiwGRNdkif4r0275k+Um35h4KMNLHF3qbKRRWvQS8Fl2rorB4efDLqrT+RvCYKPVAE+5mPF7Wbl+AiGRxYMhgPnW1+L7cUbeIwqGuo6Me/89AzrNSLyLcwXXOYTHX0aIrxJcW7fOebQowtpSoJbySVX+tByFEP2IaQgpzEIXbYM81pXmfjjvJjgEC6ZfM2P44pgeR7ORwDkRsgfndNAKU3jtVo/7fQXn2bprGdxSl2WZIOW7BgHY/naSaXWJCUMI4QzCWbXCDBnMxYLT9n1lFfPnB0/VXIckoyxWVQRRmvuKBEKPfiSRsfsfoP/792gArGgo9jMc0MHx+r56iYiAfPUnkiEHuNnmRfsws0sUta9oSRtEJvrSC51+gpZhWNB58ntNTPbFgyGBQWJRX8vC0Pokgo/waClm6lrEW/z6yO6oi9BM8MBVVdrXNbIM5yxrMKotp4wThK4gxnxqRGyCDfSA="


  file: coverage-result.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
