
sudo: required
language: java

jdk:
  - oraclejdk7
  - oraclejdk8



script:
  - mvn clean cobertura:cobertura -Dtest=SerializableTest#decodeGolden -DfailIfNoTests=false

before_deploy:
- tar -zcvf coverage-result.tar.gz /home/travis/build/leusonmario/wire/target/site/cobertura

deploy:
  provider: releases
  api_key:
    secure: "Yxee362OOYAHoeL7jFdXrKQIGpUUrG0AZ5UtXJe1YP0GANBfTLDgEwk7YLv6aQNtAzO46VCI8w2Is8qZTfXWZFsIDPf8YAQpWpWHDgAYm4RUxilES7fkE9I9yndbhsy9IPVJNszWsFDW8Kktb5BdTdxr4ijKh5jC8v7FjP4KqHVrWiQw0FDE8GLEbhDrbKKqkiSc7grVcP+ycHQPjJJ9eiQP2ovfIXw8rdMvziSMsWdX3/7GVv8ImPamtzyM2WJubhwmBAeXXCK+6llU0i6qGsWXi/50VdEzDsl5G0jF4Fi8grCZeoQCIg3ua5zt+GI/R9X+P/pCv6zTJesukFDbp4a9Il2BwduqX2XPx6pmBwDrDzatm15VwiLu9DJ1BbmyesiNtNWaJ59HZbMhOA/iXhbFhaDgLQSu8EiOPQq5tK/IexWWKdJX5IumD8tvrnBCiygusfgwtBxfWvbbJfoS1fX2V2zWEdRD+3stqKX/TpOdbmoU2y+jVufQGJYEWavcG1IF0xoiQzH8YCXQ+VYVls2OCg0De05QqQnvSkAGIGwS64STdHgd4iYnM/KunhoT/horOW2DTBCjO5nRBHiD+0aqUkVNRRnIC14z7ZkRdpEH3VZ5mW6lPZWpIdkxZOnw1ViuRnAGyG7uuQ23CtSIp6gTXAVc9Tjt+cRYeAlKIok="


  file: coverage-result.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
